version: '3'

services:

  redis:
    image: redis:7
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - ntwrk_back_end

  api:
    build: ./apps/api
    restart: always
    container_name: api
    depends_on:
      - redis
    ports:
      - 8081:8080
    environment:
      NODE_ENV: production
    networks:
      - ntwrk_back_end
      - ntwrk_front_end

  web:
    build: ./apps/web
    restart: always
    container_name: web
    ports:
      - "8080:80"
    depends_on:
      - redis
    environment:
      NODE_ENV: production
    networks:
      - ntwrk_front_end

networks:
  ntwrk_back_end: {}
  ntwrk_front_end: {}